- platform: webostv
  host: 192.168.1.132
  name: Living room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: a0:6f:aa:47:99:68
      broadcast_address: 192.168.1.132
  customize:
      sources:
        - Livetv
        - Youtube
        - Cast
        - Netflix
        - Plex
        - XBOX
- platform: cast
  host: 192.168.1.122
  name: Google Home
- platform: cast
  host: 192.168.1.120
  name: Chromecast bedroom
- platform: cast
  host: 192.168.1.121
  name: Chromecast living room

- platform: spotify
  name: Marcus Spotify
  client_id: eab25f830ae240e18ce070fa43ffb5d3
  client_secret: !secret spotify

