- platform: nmap_tracker
  hosts: 192.168.1.0/24
  consider_home: 600
  track_new_devices: yes
  interval_seconds: 30

- platform: luci
  host: 192.168.1.1
  username: !secret routeruser
  password: !secret routerpass
