# System monitoring
- platform: systemmonitor
  name: "systemmonitor"
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

# Weather
- platform: darksky
  api_key: !secret darksky
  units: si
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_intensity_max
    - precip_type

- platform: openweathermap
  api_key: d7778ea8265a129740a879026a2ebcae
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - rain


# Speedtest
- platform: speedtest
  hour:
    - 2
    - 14
  monitored_conditions:
    - ping
    - download
    - upload

# Uber 
- platform: uber
  server_token: !secret uber
  start_latitude: 59.308447
  start_longitude: 18.082513
  end_latitude: 59.288056
  end_longitude: 18.011440


# Linnéas commute
- platform: google_travel_time
  api_key: !secret google
  name: Skanstull -> Thorildsplan
  origin: Ringvägen 138, Stockholm
  destination: Lindhagensplan 70, 112 43 Stockholm
  options:
    mode: transit
    units: metric

# Skanstull to Karbin klätterhall
- platform: google_travel_time
  api_key: !secret google
  name: Skanstull -> Karbin klätterhall
  origin: Ringvägen 138, Stockholm
  destination: Västberga allé 60, 126 30 Hägersten
  options:
    mode: transit
    units: metric

- platform: yahoo_finance
  symbols:
    - FB
    - GOOGL
    - TSLA
    - AAPL

# Closet motion sensor
- platform: rest
  resource: http://192.168.1.114/api/K9VXC64UMOXj-IpVTrzZbVyIXxXRd1cuv0CRIOe7/sensors/7
  value_template: '{{ value_json.state.presence }}'
  scan_interval: 5
  name: Closet Motion
