- platform: systemmonitor
  name: "systemmonitor"
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: wlan0
  - type: network_out
    arg: wlan0
  - type: last_boot


# Weather
- platform: darksky
  api_key: !secret darksky
  units: si
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_intensity_max
    - precip_type

# Speedtest
- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

# Uber not working: https://github.com/home-assistant/home-assistant/issues/3971
- platform: uber
  server_token: !secret uber
  start_latitude: 59.308447
  start_longitude: 18.082513