# System monitoring
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

# Weather
- platform: darksky
  api_key: !secret darksky
  units: si
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_intensity_max
    - precip_type

- platform: openweathermap
  api_key: d7778ea8265a129740a879026a2ebcae
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - rain

# Uber - do I need this?
#- platform: uber
#  server_token: !secret uber
#  start_latitude: 59.308447
#  start_longitude: 18.082513
#  end_latitude: 59.288056
#  end_longitude: 18.011440


# Linnéas commute
- platform: google_travel_time
  api_key: !secret google
  origin: Ringvägen 138, Stockholm
  destination: Lindhagensplan 70, 112 43 Stockholm
  options:
    mode: transit
    units: metric

# Skanstull to Karbin klätterhall
- platform: google_travel_time
  api_key: !secret google
  origin: Ringvägen 138, Stockholm
  destination: Västberga allé 60, 126 30 Hägersten
  options:
    mode: transit
    units: metric

#- platform: alpha_vantage
#  api_key: !secret alpha
#  symbols:
#    - name: Facebook
#      symbol: FB
#      currency: USD
#    - name: Alphabet
#      symbol: GOOGL
#    - name: Tesla
#      symbol: TSLA
#    - name: Apple
#      symbol: AAPL

# Closet motion sensor
# Using https://github.com/robmarkcole/Hue-sensors-HASS instead
#- platform: rest
#  resource: http://192.168.1.114/api/K9VXC64UMOXj-IpVTrzZbVyIXxXRd1cuv0CRIOe7/sensors/7
#  value_template: '{{ value_json.state.presence }}'
#  scan_interval: 5
#  name: Closet Motion


#- platform: etherscan
#  address: '0xDE02b2B959aC48703b7666B59aA94f4973176992'
#- platform: etherscan
#  address: '0xDE02b2B959aC48703b7666B59aA94f4973176992'
#  token: VEN

- platform: mqtt
  name: door
  state_topic: "door/state"
  value_template: "{{ value_json }}"

- platform: mqtt
  name: door_battery
  state_topic: "door/battery"
  value_template: "{{ value_json }}"
  device_class: battery

- platform: mqtt
  name: window
  state_topic: "window/state"
  value_template: "{{ value_json }}"

- platform: mqtt
  name: window_battery
  state_topic: "window/battery"
  value_template: "{{ value_json }}"
  device_class: battery

- platform: template
  sensors:
    door_status:
      friendly_name: "Door status"
      value_template: >-
          {% if is_state('sensor.door', '1') %}
            open
          {% else %}
            closed
          {% endif %}

- platform: template
  sensors:
    window_status:
      friendly_name: "Window status"
      value_template: >-
          {% if is_state('sensor.window', '1') %}
            open
          {% else %}
            closed
          {% endif %}

